# Generated by Django 4.1.5 on 2023-01-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_delete_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comments',
            field=models.CharField(max_length=1000),
        ),
    ]
